In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,14,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [19]:
np.linspace(0,10,4)

array([  0.        ,   3.33333333,   6.66666667,  10.        ])

In [21]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [25]:
np.random.randn(4,4)

array([[-1.66501703,  0.7382643 ,  0.85251699, -1.37160696],
       [-0.14976335, -1.89576895,  0.37642497,  0.47796408],
       [ 0.14613764,  0.15801615, -1.60566205,  0.96422771],
       [ 1.13348063,  0.21192945,  1.96814939, -1.25381121]])

In [29]:
np.random.randint(1,100,[4,5])

array([[ 9, 95, 23, 53,  2],
       [99, 91, 62, 99, 64],
       [27,  9, 84, 96, 97],
       [20, 13, 36, 49, 30]])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([18, 14, 28, 16, 37, 18,  1, 49,  4, 27])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr.max()

49

In [38]:
ranarr.min()

1

In [39]:
ranarr.argmax()

7

In [40]:
ranarr.argmin()

6

In [41]:
arr.shape

(25,)

In [42]:
arr = arr.reshape(5,5)

In [43]:
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int64')

In [45]:
arr = np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[8]

8

In [50]:
arr[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[0:5] = 100

In [52]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
arr = np.arange(0,11)

In [54]:
slice_of_arr = arr[0:6]

In [55]:
slice_of_arr[:] = 99

In [56]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr_copy = arr.copy()

In [58]:
arr_copy[:] = 100

In [59]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [66]:
arr_2d[1][1]

25

In [68]:
arr_2d[2,1]

40

In [69]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [70]:
arr = np.arange(0,11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
bool_arr = arr > 5

In [74]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [75]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [76]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [77]:
arr[arr<3]

array([0, 1, 2])

In [79]:
arr = np.arange(0,11)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [82]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [84]:
5 * arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [85]:
arr * 17

array([  0,  17,  34,  51,  68,  85, 102, 119, 136, 153, 170])

In [91]:
arr / 100

array([ 0.  ,  0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,
        0.09,  0.1 ])

In [93]:
arr / arr

/home/dark/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [94]:
1 / arr

/home/dark/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [95]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [96]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [97]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [99]:
arr.max()

10

In [100]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [101]:
np.log(arr)

/home/dark/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])